var CheckEvent = require('../../models/checkEvent');
var PagerDuty = require('pagerduty');

//Convert to Set implementation
var activeAlerts = [];

exports.initWebApp = function(options) {
  	var config = options.config.pagerduty;
	var pager = new PagerDuty({serviceKey:config.serviceKey});

	var addAlert = function(incident){
		activeAlerts.push(incident);
	}

	var incidentExists = function(id){
		return getIncident(id) === undefined ? false : true;
	}

	var getIncident = function(id){
		activeAlerts.foreach(function(incident){
			if(incident.id === id) {
				return true;
			}
		});
		return false;
	}

 	CheckEvent.on('afterInsert', function(checkEvent) {
	    checkEvent.findCheck(function(findErr, check) {
	    	console.log(check);
	    	console.log(checkEvent);
	      	if(!check.isUp){
			    pager.create({
					incidentKey: checkEvent._id,
					description: 'Uptime down: ' + check.name,
					details:'Automatic alert generated by Uptime: ' + checkEvent.message,
					callback: function(err,response){
						if(err){
							console.log(err);
						} else {
							console.log(response);
							addAlert({ id : check._id, incident_key : response.incident_key});
						}
					}
				});
			} else if(check.isUp){
				if(incidentExists(check.id)){
					var incident = getIncident(id);
					var incident_key = incident.incident_key;

					console.log(incident_key);

					pager.resolve({
						incidentKey : incident_key,
						description: 'Uptime up: ' + check.name,
						details:'Automatic alert generated by Uptime: ' + checkEvent.message,
						callback: function(err,response){
							if(err){
								console.log(err);
							} else {
								console.log(response);
							}
						}
					});
				}
			}
    	});
  });
}